name: CI

on:
  workflow_dispatch:
  release:
    types: [published]
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      PROJECT: 'TypeExtensions.PocoBuilder.csproj'
      
    defaults:
      run:
        working-directory: ./src/TypeExtensions.PocoBuilder

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Extract version from tag
      uses: damienaicheh/extract-version-from-tag-action@v1.0.0
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.1.1

    - name: Restore dependencies
      run: dotnet restore $PROJECT

    - name: Build
      run: dotnet build $PROJECT --configuration $BUILD_CONFIG -p:Version=${{format('{0}.{1}.{2}', env.MAJOR, env.MINOR, env.PATH)}} --no-restore

    - name: Run tests
      run: dotnet test /p:Configuration=$env:BUILD_CONFIG --no-restore --no-build --verbosity normal
      
    - name: Publish
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
