name: CI

on:
  workflow_dispatch:
  release:
    types: [published]
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      
    defaults:
      run:
        working-directory: ./src/TypeExtensions.PocoBuilder

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Extract version from tag
      uses: damienaicheh/extract-version-from-tag-action@v1.0.0
        
    - name: SonarCloud Scan
      uses: highbyte/sonarscan-dotnet@v2.1.3
      with:
        sonarProjectKey: amileszko_type-extensions-poco-builder
        sonarProjectName: type-extensions-poco-builder
        sonarOrganization: amileszko
        dotnetBuildArguments: --configuration $BUILD_CONFIG -p:Version=${{format('{0}.{1}.{2}', env.MAJOR, env.MINOR, env.PATCH)}}
        dotnetTestArguments: --logger trx --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
        sonarBeginArguments: /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" -d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.1.1

    - name: Run tests
      run: dotnet test --configuration $BUILD_CONFIG --no-restore --no-build --verbosity normal
      
    - name: Pack
      run: dotnet pack --configuration $BUILD_CONFIG --no-restore --no-build --verbosity normal
      
    - name: Publish to NuGet
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}} -SkipDuplicate
      
    - name: Publish to GitHub
      run: nuget push **\*.nupkg -Source 'https://nuget.pkg.github.com/amileszko/index.json' -ApiKey ${{secrets.MY_GITHUB_PAT}} -SkipDuplicate
