name: CI

on:
  workflow_dispatch:
  release:
    types: [published]
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      PROJECT: 'TypeExtensions.PocoBuilder.csproj'

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Extract version from tag
      uses: damienaicheh/extract-version-from-tag-action@v1.0.0

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore dependencies
      run: nuget restore $PROJECT

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6

    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG -p:Version=format('{{{0}.{1}.{2}}}', $MAJOR, $MINOR, $PATH) --no-restore

    - name: Run tests
      run: dotnet test /p:Configuration=$env:BUILD_CONFIG --no-restore --no-build --verbosity normal
      
    - name: Publish
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
